config/routes.rb
Rails.application.routes.draw do
  resources :boxscores
  resources :games
  resources :players
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boxscore.rb
class Boxscore < ApplicationRecord
  belongs_to :player
  belongs_to :game
  validates :points, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :rebounds, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :assists, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validate :already_has_game?

  def game_info(game)
    "#{self.game.opponent} - #{self.game.readable_datetime}"
  end

  def already_has_game?
    box = Boxscore.find_by(player_id: self.player.id, game_id: self.game.id)
    if box
      errors.add(:player, "already has a boxscore for this game")
    end
  end

end

app/models/game.rb
class Game < ApplicationRecord
  has_many :boxscores
  has_many :players, through: :boxscores
  validates :date, presence: true
  validates :opponent, presence: true, length: { is: 3 }

  def readable_datetime
    "#{self.date.strftime('%B %d, %Y')}"
  end

  def game_info
    "#{self.opponent} - #{self.readable_datetime}"
  end

end

app/models/player.rb
class Player < ApplicationRecord
  has_many :boxscores
  has_many :players, through: :boxscores
  validates :name, presence: true
  validates :age, presence: true, numericality: { only_integer: true }
  validates :team, presence: true, length: { is: 3 }
  validates :jersey, presence: true, numericality: { only_integer: true }
  validate :unique_jersey

  def unique_jersey
    other_player = Player.find_by(team: self.team, jersey: self.jersey)
    if other_player
      errors.add(:jersey, "cannot have same jersey number as teammate")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boxscores_controller.rb
class BoxscoresController < ApplicationController
  before_action :find_boxscore, only: [:show, :edit, :update, :destroy]

  def index
    @boxscores = Boxscore.all
  end

  def show
    #code
  end

  def new
    @boxscore = Boxscore.new
    @players = Player.all
    @games = Game.all
  end

  def create
    @boxscore = Boxscore.new(boxscore_params)
    if @boxscore.save
      redirect_to @boxscore
    else
      flash[:errors] = @boxscore.errors.full_messages
      redirect_to new_boxscore_path
    end
  end

  def edit
    #code
  end

  def update
    if @boxscore.update(boxscore_params)
      redirect_to @boxscore
    else
      flash[:errors] = @boxscore.errors.full_messages
      redirect_to edit_boxscore_path
    end
  end

  def destroy
    @boxscore.destroy
    redirect_to new_boxscore_path
  end

  private

  def find_boxscore
    @boxscore = Boxscore.find(params[:id])
  end

  def boxscore_params
    params.require(:boxscore).permit(:points, :rebounds, :assists, :player_id, :game_id)
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :find_game, only: [:show, :edit, :update, :destroy]

  def index
    @games = Game.all
  end

  def show
    #code
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to @game
    else
      flash[:errors] = @game.errors.full_messages
      redirect_to new_game_path
    end
  end

  def edit
    #code
  end

  def update
    if @game.update(game_params)
      redirect_to @game
    else
      flash[:errors] = @game.errors.full_messages
      redirect_to edit_game_path
    end
  end

  def destroy
    @game.destroy
    redirect_to games_path
  end

  private

  def find_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:date, :opponent, :home)
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :find_player, only: [:show, :edit, :update, :destroy]

  def index
    @players = Player.all
  end

  def show
    #code
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to @player
    else
      flash[:errors] = @player.errors.full_messages
      redirect_to new_player_path
    end
  end

  def edit
    #code
  end

  def update
    if @player.update(player_params)
      redirect_to @player
    else
      flash[:errors] = @player.errors.full_messages
      redirect_to edit_player_path
    end
  end

  def destroy
    @player.destroy
    redirect_to players_path
  end

  private

  def find_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:name, :age, :team, :jersey)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boxscores_helper.rb
module BoxscoresHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/boxscores/edit.erb
<h1>New Boxscore Form</h1>

<ol>
  <% if flash[:errors] %>
    <strong>Errors</strong>
    <% flash[:errors].each do |error| %>
      <li><%= error %></li>
    <% end %>
  <% end %>
</ol>

<%= form_for @boxscore do |f| %>
  <%= f.collection_select :player_id, @players, :id, :name, prompt: 'Select Player' %>
  <%= f.collection_select :game_id, @games, :id, :game_info, prompt: 'Select Game' %>
  <%= f.label :points %>
  <%= f.number_field :points %>
  <%= f.label :rebounds %>
  <%= f.number_field :rebounds %>
  <%= f.label :assists %>
  <%= f.number_field :assists %>
  <%= f.submit %>
<% end %>

app/views/boxscores/index.erb
No index page for individual boxscore - visit the game or player page

app/views/boxscores/new.erb
<h1>New Boxscore Form</h1>

<ol>
  <% if flash[:errors] %>
    <strong>Errors</strong>
    <% flash[:errors].each do |error| %>
      <li><%= error %></li>
    <% end %>
  <% end %>
</ol>

<%= form_for @boxscore do |f| %>
  <%= f.collection_select :player_id, @players, :id, :name, prompt: 'Select Player' %>
  <%= f.collection_select :game_id, @games, :id, :game_info, prompt: 'Select Game' %>
  <%= f.label :points %>
  <%= f.number_field :points %>
  <%= f.label :rebounds %>
  <%= f.number_field :rebounds %>
  <%= f.label :assists %>
  <%= f.number_field :assists %>
  <%= f.submit %>
<% end %>

app/views/boxscores/show.erb
<h1> View Boxscore </h1>

Player Name: <%= link_to @boxscore.player.name, player_path(@boxscore.player) %><br>
Game: <%= link_to @boxscore.game_info(@boxscore.game), game_path(@boxscore.game) %>

<table>
  <tr>
    <th>Points</th>
    <th>Rebounds</th>
    <th>Assists</th>
  </tr>
  <tr>
    <td><%= @boxscore.points %></td>
    <td><%= @boxscore.rebounds %></td>
    <td><%= @boxscore.assists %></td>
  </tr>
</table>


<%= form_for @boxscore do |f| %>
  <%= button_to "Delete Boxscore?", @boxscore, :method => :delete %>
<% end %>

app/views/games/edit.erb
<h1> Edit A Game </h1>

<ol>
  <% if flash[:errors] %>
    <strong>Errors</strong>
    <% flash[:errors].each do |error| %>
      <li><%= error %></li>
    <% end %>
  <% end %>
</ol>

<%= form_for @game do |f| %>
  <%= f.label :date %>
  <%= f.datetime_select :date, :ampm => true, :minute_step => 30 %>
  <%= f.label :opponent %>
  <%= f.text_field :opponent %>
  <%= f.label :home %>
  <%= f.check_box :home %>
  <%= f.submit %>
<% end %>

app/views/games/index.erb
<h1> Celtics Game Index </h1>

<ul>
  <% @games.each do |game| %>
    <%= link_to game.game_info, game %><br>
  <% end %>
</ul>

app/views/games/new.erb
<h1> New Game Form </h1>

<ol>
  <% if flash[:errors] %>
    <strong>Errors</strong>
    <% flash[:errors].each do |error| %>
      <li><%= error %></li>
    <% end %>
  <% end %>
</ol>

<%= form_for @game do |f| %>
  <%= f.label :date %>
  <%= f.datetime_select :date, :ampm => true, :minute_step => 30 %>
  <%= f.label :opponent %>
  <%= f.text_field :opponent %>
  <%= f.label :home %>
  <%= f.check_box :home %>
  <%= f.submit %>
<% end %>

app/views/games/show.erb
<h1> Celtics Game Details </h1>

Date: <%= @game.readable_datetime %><br>
Opponent: <%= @game.opponent %><br>
Home/Away: <%= @game.home ? "Home" : "Away" %><br>

Player Boxscores:
<ul>
  <% @game.players.each do |player| %>
    <%= link_to player.name, boxscore_path(player.boxscores.find_by(game_id: @game.id)) %><br>
  <% end %>
</ul>

<%= form_for @game do |f| %>
  <%= button_to "Delete Game?", @game, :method => :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bballbox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/edit.erb
<h1> Edit a Player </h1>

<ol>
  <% if flash[:errors] %>
    <strong>Errors</strong>
    <% flash[:errors].each do |error| %>
    <li> <%= error %> </li>
    <% end %>
  <% end %>
</ol>

<%= form_for @player do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :age %>
  <%= f.number_field :age %>
  <%= f.label :team %>
  <%= f.text_field :team %>
  <%= f.label :jersey %>
  <%= f.number_field :jersey %>
  <%= f.submit %>
<% end %>

app/views/players/index.erb
<h1> Player Index </h1>

<ul>
  <% @players.each do |player| %>
    <%= link_to player.name, player %><br>
  <% end %>
</ul>

app/views/players/new.erb
<h1> New Player Form </h1>

<ol>
  <% if flash[:errors] %>
    <strong>Errors</strong>
    <% flash[:errors].each do |error| %>
    <li> <%= error %> </li>
    <% end %>
  <% end %>
</ol>

<%= form_for @player do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :age %>
  <%= f.number_field :age %>
  <%= f.label :team %>
  <%= f.text_field :team %>
  <%= f.label :jersey %>
  <%= f.number_field :jersey %>
  <%= f.submit %>
<% end %>

app/views/players/show.erb
<h1><%= @player.name %> Player Page</h1>

Age: <%= @player.age %><br>
Team: <%= @player.team %><br>
Jersey #: <%= @player.jersey %><br>

<% @player.boxscores.each do |boxscore| %>
  Boxscore: <%= link_to boxscore.game_info(boxscore.game), boxscore  %><br>
<% end %>


<%= form_for @player do |f| %>
  <%= button_to "Delete Player?", @player, :method => :delete %>
<% end %>